(load "actr7.x/load-act-r.lisp")
(load "geomates/act-r-experiment.lisp")
(load "geomates/levels.lisp")
(load "code/navigation-functions.lisp")
(load-act-r-model "code/model-shengyong-jiang.lisp")
;; (load-act-r-model "code/DeepSeekAgent.lisp")
(run-environment)